profile_name = "test_profile"
teensy_version = "TEENSY40"
test = true
profile_description = "Used for testing"

[[devices]]
device_name = "pot_01"
device_type = "potentiometer"
signal_type = "analog"
io = "input"
pin_number = 0

[[devices]]
device_name = "red_led"
device_type = "led"
signal_type = "digital"
io = "output"
pin_number = 15

[[devices]]
device_name = "green_led"
device_type = "led"
signal_type = "digital"
io = "output"
pin_number = 16

[[devices]]
device_name = "blue_led"
device_type = "led"
signal_type = "digital"
io = "output"
pin_number = 17

[[devices]]
device_name = "but_01"
device_type = "button"
signal_type = "digital"
io = "input"
pin_number = 18
