// THIS SKETCH HAS BEEN GENERATED BY ModularInstrumentPanel
//      https://github.com/sean-delcastillo/ModularInstrumentPanel
// 13/01/2023 17:09:46

int pot_01 = 0;
int red_led = 15;
int green_led = 16;
int blue_led = 17;

void setup() {
    pinMode(0, INPUT);
    pinMode(15, OUTPUT);
    pinMode(16, OUTPUT);
    pinMode(17, OUTPUT);

    Serial.begin(38400);
}

void loop() {
    Serial.print("Analog 0 is: ");
    Serial.println(analogRead(pot_01));
    delay(50);

    digitalWrite(red_led, HIGH);
    delay(200);
    digitalWrite(red_led, LOW);
    delay(200);

    digitalWrite(green_led, HIGH);
    delay(200);
    digitalWrite(green_led, LOW);
    delay(200);

    digitalWrite(blue_led, HIGH);
    delay(200);
    digitalWrite(blue_led, LOW);
    delay(200);

}