// THIS SKETCH HAS BEEN GENERATED BY ModularInstrumentPanel
//      https://github.com/sean-delcastillo/ModularInstrumentPanel
// 18/01/2023 17:48:42

#include <stdlib.h>

#include <Metro.h>
#include <Bounce.h>

int pot_01 = 0;
int red_led = 15;
int green_led = 16;
int blue_led = 17;


Metro serialMetro = Metro(250);
Metro delayMetro = Metro(200);

int pot_01_last_read = 0;

void setup() {
    pinMode(0, INPUT);
    pinMode(15, OUTPUT);
    pinMode(16, OUTPUT);
    pinMode(17, OUTPUT);

    Serial.begin(38400);
}

void loop() {
    if (serialMetro.check() == 1) {
        int pot_01_current_read = analogRead(pot_01);
        if (abs(pot_01_last_read - pot_01_current_read) >= 3) {
            Serial.print("[Potentionmeter] pot_01 on pin 0 is: ");
            Serial.println(pot_01_current_read);
            pot_01_last_read = pot_01_current_read;
        }
    }

    if (delayMetro.check() == 1) {
        digitalToggle(red_led);
    }

    if (delayMetro.check() == 1) {
        digitalToggle(green_led);
    }

    if (delayMetro.check() == 1) {
        digitalToggle(blue_led);
    }

}